# Generated by Django 4.2.14 on 2025-09-19 12:19

import Utente.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utente', '0002_alter_registrati_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrati',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, validators=[Utente.models.valida_numero_telefono]),
        ),
    ]
