# Generated by Django 4.2.14 on 2025-09-24 19:03

import Utente.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utente', '0003_alter_registrati_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, validators=[Utente.models.valida_numero_telefono]),
        ),
    ]
