# Generated by Django 5.2.6 on 2026-07-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvvisoChiusura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inizio', models.DateField()),
                ('data_fine', models.DateField()),
                ('motivo_chiusura', models.CharField(max_length=200)),
                ('attivo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Avviso di chiusura',
                'verbose_name_plural': 'Avvisi di chiusura',
            },
        ),
    ]
