# Generated by Django 5.2.6 on 2026-07-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avvisi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avvisochiusura',
            options={'ordering': ('-data_inizio',), 'verbose_name': 'Avviso di chiusura', 'verbose_name_plural': 'Avvisi di chiusura'},
        ),
        migrations.AlterField(
            model_name='avvisochiusura',
            name='motivo_chiusura',
            field=models.CharField(help_text='Minuscolo, completa la frase "...chiusa dal X al Y compresi per ___" (es. "ferie estive", "festività natalizie").', max_length=200),
        ),
    ]
