# Generated by Django 5.2.6 on 2026-07-27 16:04

import datetime

from django.db import migrations


def crea_avviso_ferie_estive_2026(apps, schema_editor):
    AvvisoChiusura = apps.get_model("Avvisi", "AvvisoChiusura")
    AvvisoChiusura.objects.get_or_create(
        data_inizio=datetime.date(2026, 8, 7),
        data_fine=datetime.date(2026, 8, 23),
        motivo_chiusura="ferie estive",
    )


def rimuovi_avviso_ferie_estive_2026(apps, schema_editor):
    AvvisoChiusura = apps.get_model("Avvisi", "AvvisoChiusura")
    AvvisoChiusura.objects.filter(
        data_inizio=datetime.date(2026, 8, 7),
        data_fine=datetime.date(2026, 8, 23),
        motivo_chiusura="ferie estive",
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('Avvisi', '0002_alter_avvisochiusura_options_and_more'),
    ]

    operations = [
        migrations.RunPython(crea_avviso_ferie_estive_2026, rimuovi_avviso_ferie_estive_2026),
    ]
