# Generated by Django 5.2.6 on 2026-09-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avvisi', '0003_crea_avviso_ferie_estive_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avvisochiusura',
            name='motivo_chiusura',
            field=models.CharField(max_length=200),
        ),
    ]
