# Generated by Django 5.2.6 on 2026-09-04 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Avvisi', '0004_alter_avvisochiusura_motivo_chiusura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avvisochiusura',
            options={'ordering': ('data_inizio',), 'verbose_name': 'Avviso di chiusura', 'verbose_name_plural': 'Avvisi di chiusura'},
        ),
    ]
