# Generated by Django 5.2.6 on 2026-09-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avvisi', '0005_alter_avvisochiusura_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestiPillolaOrari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo_aperto', models.CharField(default='Siamo aperti', max_length=200)),
                ('testo_vicino_chiusura', models.CharField(default='Aperti ma vicini alla chiusura', max_length=200)),
                ('testo_pranzo', models.CharField(default='Chiusura per pranzo', max_length=200)),
                ('testo_chiuso_feriale', models.CharField(default='Chiusi, ci vediamo domani dalle ore 8', max_length=200)),
                ('testo_chiuso_weekend', models.CharField(default='Chiusi il fine settimana, ci vediamo Lunedì dalle ore 8', max_length=200)),
            ],
            options={
                'verbose_name': 'Testi pillola orari',
                'verbose_name_plural': 'Testi pillola orari',
            },
        ),
    ]
