# Generated by Django 5.2.6 on 2026-07-17 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_cat', to='Pagine.categoriafile'),
        ),
    ]
