# Generated by Django 5.2.6 on 2026-09-05 11:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagine', '0003_alter_file_categoria_obbligatoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='creato_il',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='modificato_il',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
