# Generated by Django 4.2.14 on 2024-07-23 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dettaglio_Preventivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato', models.TextField(choices=[('inviato', 'inviato'), ('errore', 'errore')], default='inviato')),
                ('messaggio', models.TextField(blank=True, max_length=400, null=True)),
                ('luogo', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'verbose_name': 'Dettaglio Preventivo',
                'verbose_name_plural': 'Dettagli Preventivi',
                'db_table': 'Dettaglio Preventivo',
            },
        ),
        migrations.CreateModel(
            name='Elementi_Preventivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Elemento_Preventivo',
                'verbose_name_plural': 'Elementi_Preventivi',
                'db_table': 'Elemento_Preventivo',
            },
        ),
        migrations.CreateModel(
            name='Preventivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=datetime.datetime(2024, 7, 23, 12, 16, 59, 478302))),
            ],
            options={
                'verbose_name': 'Preventivo',
                'verbose_name_plural': 'Preventivi',
                'db_table': 'Preventivo',
            },
        ),
    ]
