# Generated by Django 4.2.14 on 2024-07-27 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Prodotti', '0001_initial'),
        ('Preventivo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='preventivo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordini', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='elementi_preventivo',
            name='preventivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementi_preventivo', to='Preventivo.preventivo'),
        ),
        migrations.AddField(
            model_name='elementi_preventivo',
            name='prodotto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prodotti.prodotto'),
        ),
        migrations.AddField(
            model_name='dettaglio_preventivo',
            name='preventivo',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='dettaglio_preventivo', to='Preventivo.preventivo'),
        ),
    ]
