# Generated by Django 4.2.10 on 2024-03-05 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Preventivo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Prodotti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventivo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordini', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='elementi_preventivo',
            name='preventivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Preventivo.preventivo'),
        ),
        migrations.AddField(
            model_name='elementi_preventivo',
            name='prodotto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prodotti.prodotto'),
        ),
        migrations.AddField(
            model_name='dettaglio_preventivo',
            name='preventivo',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='dettaglio_preventivo', to='Preventivo.preventivo'),
        ),
    ]
