# Generated by Django 4.2.10 on 2024-03-06 10:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Preventivo', '0004_alter_preventivo_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementi_preventivo',
            name='preventivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementi_preventivo', to='Preventivo.preventivo'),
        ),
        migrations.AlterField(
            model_name='preventivo',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 6, 11, 2, 5, 711253)),
        ),
    ]
