# Generated by Django 4.1 on 2024-03-07 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preventivo', '0005_alter_elementi_preventivo_preventivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preventivo',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 7, 14, 50, 15, 686600)),
        ),
    ]
