# Generated by Django 4.2.11 on 2024-03-20 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prodotti', '0022_alter_immaginiarticolo_immagine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immaginiarticolo',
            name='immagine',
            field=models.ImageField(null=True, upload_to='immagini_articoli/'),
        ),
        migrations.AlterField(
            model_name='schedetecniche',
            name='data_inizio',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 20, 15, 42, 2, 386733)),
        ),
    ]
