# Generated by Django 4.2.14 on 2024-07-23 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Carrello', '0001_initial'),
        ('Prodotti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrello',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementi_carrello', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carrello',
            name='prodotto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prodotti.prodotto'),
        ),
    ]
