# Generated by Django 4.1 on 2024-03-21 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prodotti', '0023_alter_immaginiarticolo_immagine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedetecniche',
            name='data_inizio',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 21, 17, 59, 55, 534488)),
        ),
        migrations.AlterField(
            model_name='sottocategoria',
            name='codice_sottocategoria',
            field=models.IntegerField(default=99, unique=True),
        ),
    ]
