# Generated by Django 4.2.10 on 2024-03-05 14:55

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=30)),
                ('cognome_ragione_sociale', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=150)),
                ('indirizzo', models.CharField(blank=True, max_length=255)),
                ('citta', models.CharField(blank=True, max_length=255)),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
            ],
            options={
                'verbose_name_plural': 'Clienti',
                'db_table': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='Messaggi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenuto', models.TextField(blank=True, max_length=400)),
            ],
            options={
                'verbose_name_plural': 'Messaggi',
                'db_table': 'Messaggio',
            },
        ),
        migrations.CreateModel(
            name='Registrati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('cognome_ragione_sociale', models.CharField(blank=True, max_length=50)),
                ('codiceFiscale_PartitaIVA', models.CharField(max_length=16)),
                ('indirizzo', models.CharField(blank=True, max_length=255)),
                ('citta', models.CharField(blank=True, max_length=255)),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Registrati',
                'db_table': 'Registrati',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Richiesta_messaggio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_richiesta', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Utente.cliente')),
                ('messaggio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Utente.messaggi')),
            ],
            options={
                'verbose_name_plural': 'Richiesta_messaggi',
                'db_table': 'Richiesta_messaggio',
            },
        ),
    ]
