# Generated by Django 4.1 on 2024-03-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrati',
            name='email',
            field=models.EmailField(max_length=40, unique=True),
        ),
    ]
