# Generated by Django 4.1 on 2024-03-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utente', '0002_alter_registrati_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrati',
            name='username',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
