# Generated by Django 4.2.14 on 2024-07-27 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preventivo', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preventivo',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 27, 19, 22, 55, 622289)),
        ),
    ]
