# Generated by Django 4.2.14 on 2025-09-19 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preventivo', '0010_alter_preventivo_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preventivo',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 19, 14, 19, 28, 154502)),
        ),
    ]
