# Generated by Django 4.2.14 on 2025-09-24 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preventivo', '0024_alter_preventivo_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preventivo',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 24, 21, 3, 25, 499057)),
        ),
    ]
