# Generated by Django 5.2.6 on 2026-09-12 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preventivo', '0029_alter_preventivo_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dettaglio_preventivo',
            name='preventivo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dettaglio_preventivo', to='Preventivo.preventivo'),
        ),
    ]
