# Generated by Django 5.2.6 on 2026-09-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preventivo', '0030_alter_dettaglio_preventivo_preventivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dettaglio_preventivo',
            name='messaggio',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
