# Generated by Django 5.2.6 on 2026-09-12 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Preventivo', '0031_alter_dettaglio_preventivo_messaggio'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dettaglio_preventivo',
            table='Dettaglio_Preventivo',
        ),
    ]
