# Generated by Django 5.2.6 on 2026-09-12 22:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preventivo', '0032_alter_dettaglio_preventivo_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementi_preventivo',
            name='quantita',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
