# Generated by Django 5.2.6 on 2026-09-12 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preventivo', '0033_alter_elementi_preventivo_quantita'),
        ('Prodotti', '0037_alter_prodotto_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementi_preventivo',
            name='prodotto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementi_preventivo', to='Prodotti.prodotto'),
        ),
    ]
