# Generated by Django 5.2.6 on 2026-09-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preventivo', '0034_alter_elementi_preventivo_prodotto'),
        ('Prodotti', '0037_alter_prodotto_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='elementi_preventivo',
            constraint=models.UniqueConstraint(fields=('preventivo', 'prodotto'), name='vincolo_unico_preventivo_prodotto'),
        ),
    ]
