# Generated by Django 5.2.6 on 2026-09-12 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Preventivo', '0035_elementi_preventivo_vincolo_unico_preventivo_prodotto'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='elementi_preventivo',
            table='Elementi_Preventivo',
        ),
    ]
