# Generated by Django 5.2.6 on 2026-09-13 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Preventivo', '0036_alter_elementi_preventivo_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preventivo',
            options={'ordering': ['-data'], 'verbose_name': 'Preventivo', 'verbose_name_plural': 'Preventivi'},
        ),
    ]
