# Generated by Django 4.2.14 on 2024-07-27 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_file', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(null=True, upload_to='documenti/')),
                ('categoria', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_cat', to='Pagine.categoriafile')),
            ],
        ),
    ]
