# Generated by Django 4.2.14 on 2024-07-27 16:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(blank=True, max_length=30)),
                ('immagine_categoria', models.ImageField(default='logo/saniscope_logo 2.png', upload_to='immagini_categoria/')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorie',
                'db_table': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice_prodotto', models.CharField(blank=True, max_length=10)),
                ('nome_prodotto', models.CharField(blank=True, max_length=30)),
                ('descrizione', models.CharField(blank=True, max_length=250, null=True)),
                ('unita_di_misura', models.CharField(max_length=2, null=True)),
                ('gruppo', models.IntegerField(null=True)),
                ('sottocategoriaGestionale', models.IntegerField(null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Prodotti.categoria')),
            ],
            options={
                'verbose_name': 'Prodotto',
                'verbose_name_plural': 'Prodotti',
                'db_table': 'Prodotto',
            },
        ),
        migrations.CreateModel(
            name='Sottocategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_sottocategoria', models.CharField(blank=True, max_length=30, verbose_name='nome_sottocategoria')),
                ('codice_sottocategoria', models.IntegerField(default=99, unique=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Prodotti.categoria')),
            ],
            options={
                'verbose_name': 'Sottocategoria',
                'verbose_name_plural': 'Sottocategorie',
                'db_table': 'Sottocategoria',
            },
        ),
        migrations.CreateModel(
            name='SchedeTecniche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inizio', models.DateTimeField(default=datetime.datetime(2024, 7, 27, 18, 52, 23, 324444))),
                ('data_fine', models.DateTimeField(null=True)),
                ('scheda', models.FileField(null=True, upload_to='schede_tecniche/')),
                ('articolo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheda_rel', to='Prodotti.prodotto')),
            ],
            options={
                'verbose_name': 'SchedeTecnica',
                'verbose_name_plural': 'SchedeTecniche',
                'db_table': 'SchedeTecnica',
            },
        ),
        migrations.AddField(
            model_name='prodotto',
            name='sottocategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Prodotti.sottocategoria', to_field='codice_sottocategoria'),
        ),
        migrations.CreateModel(
            name='ImmaginiArticolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immagine', models.ImageField(null=True, upload_to='immagini_articoli/')),
                ('articolo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='immagine_rel', to='Prodotti.prodotto')),
            ],
            options={
                'verbose_name': 'ImmaginiArticolo',
                'verbose_name_plural': 'ImmaginiArticoli',
                'db_table': 'ImmaginiArticolo',
            },
        ),
    ]
