# Generated by Django 4.2.14 on 2024-07-28 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prodotti', '0002_alter_schedetecniche_data_inizio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedetecniche',
            name='data_inizio',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 28, 11, 38, 12, 221422)),
        ),
    ]
