# Generated by Django 4.2.14 on 2024-12-09 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prodotti', '0006_alter_sottocategoria_options_prodotto_precursore_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto',
            name='nome_prodotto',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='schedetecniche',
            name='data_inizio',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 9, 17, 51, 11, 827652)),
        ),
    ]
