# Generated by Django 4.2.14 on 2025-09-19 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prodotti', '0007_alter_prodotto_nome_prodotto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedetecniche',
            name='data_inizio',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 19, 14, 3, 20, 106308)),
        ),
    ]
