# Generated by Django 4.2.14 on 2025-09-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prodotti', '0030_alter_schedetecniche_data_inizio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto',
            name='unita_di_misura',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
