# Generated by Django 4.2.14 on 2025-09-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prodotti', '0031_alter_prodotto_unita_di_misura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto',
            name='nome_prodotto',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
