# Generated by Django 5.2.6 on 2026-07-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prodotti', '0032_alter_prodotto_nome_prodotto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto',
            name='precursore',
            field=models.FileField(blank=True, default='documenti/Regolamento-2019-1148_esplosivi.pdf', null=True, upload_to='documenti/'),
        ),
    ]
