# Generated by Django 5.2.6 on 2026-07-22 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prodotti', '0034_popola_precursore_da_normativa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sottocategoria',
            options={'verbose_name': 'Sottocategoria', 'verbose_name_plural': 'Sottocategorie'},
        ),
        migrations.AlterModelTable(
            name='sottocategoria',
            table='Sottocategoria',
        ),
    ]
