# Generated by Django 5.2.6 on 2026-07-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prodotti', '0035_alter_sottocategoria_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto',
            name='precursore',
            field=models.FileField(blank=True, default='', null=True, upload_to='documenti/'),
        ),
    ]
