# Generated by Django 5.2.6 on 2026-08-04 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prodotti', '0036_alter_prodotto_precursore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prodotto',
            options={'ordering': ['codice_prodotto'], 'verbose_name': 'Prodotto', 'verbose_name_plural': 'Prodotti'},
        ),
    ]
