# Generated by Django 5.2.6 on 2026-09-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prodotti', '0037_alter_prodotto_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome_categoria',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
