# Generated by Django 5.2.6 on 2026-09-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prodotti', '0038_alter_categoria_nome_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sottocategoria',
            name='nome_sottocategoria',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
