# Generated by Django 5.2.6 on 2026-09-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prodotti', '0039_alter_sottocategoria_nome_sottocategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sottocategoria',
            name='nome_sottocategoria',
            field=models.CharField(max_length=30),
        ),
        migrations.AddConstraint(
            model_name='sottocategoria',
            constraint=models.UniqueConstraint(fields=('categoria', 'nome_sottocategoria'), name='sottocategoria_unica_per_categoria'),
        ),
    ]
