# Generated by Django 5.2.6 on 2026-09-13 16:50

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prodotti', '0040_alter_sottocategoria_nome_sottocategoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome_categoria',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nome_categoria'), name='categoria_nome_case_insensitive'),
        ),
    ]
