# Generated by Django 5.2.6 on 2026-09-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prodotti', '0041_alter_categoria_nome_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='categoria',
            name='categoria_nome_case_insensitive',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome_categoria',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
