# Generated by Django 5.2.6 on 2026-09-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prodotti', '0042_remove_categoria_categoria_nome_case_insensitive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome_categoria',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
