# Generated by Django 5.2.6 on 2026-09-13 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prodotti', '0043_alter_categoria_nome_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sottocategoria',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prodotti.categoria'),
        ),
    ]
