# Generated by Django 5.2.6 on 2026-09-13 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prodotti', '0044_alter_sottocategoria_categoria'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sottocategoria',
            name='sottocategoria_unica_per_categoria',
        ),
    ]
