# Generated by Django 5.2.6 on 2026-09-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prodotti', '0045_remove_sottocategoria_sottocategoria_unica_per_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sottocategoria',
            name='codice_sottocategoria',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
