# Generated by Django 5.2.6 on 2026-09-13 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prodotti', '0046_alter_sottocategoria_codice_sottocategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prodotti.categoria'),
        ),
    ]
