# Generated by Django 5.2.6 on 2026-09-13 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prodotti', '0047_alter_prodotto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Prodotti.categoria'),
        ),
    ]
