# Generated by Django 5.2.6 on 2026-09-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prodotti', '0048_alter_prodotto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto',
            name='codice_prodotto',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='descrizione',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='nome_prodotto',
            field=models.CharField(max_length=300),
        ),
    ]
