# Generated by Django 5.2.6 on 2026-09-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prodotti', '0049_alter_prodotto_codice_prodotto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto',
            name='gruppo',
            field=models.IntegerField(default=0),
        ),
    ]
