# Generated by Django 5.2.6 on 2026-09-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prodotti', '0050_alter_prodotto_gruppo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto',
            name='descrizione',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
