# Generated by Django 5.2.6 on 2026-09-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prodotti', '0051_alter_prodotto_descrizione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto',
            name='sottocategoriaGestionale',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
