# Generated by Django 5.2.6 on 2026-09-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prodotti', '0052_alter_prodotto_sottocategoriagestionale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto',
            name='precursore',
            field=models.FileField(blank=True, default='', upload_to='documenti/'),
        ),
    ]
