# Generated by Django 5.2.6 on 2026-09-13 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prodotti', '0053_alter_prodotto_precursore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immaginiarticolo',
            name='articolo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='immagine_rel', to='Prodotti.prodotto'),
        ),
        migrations.AlterField(
            model_name='immaginiarticolo',
            name='immagine',
            field=models.ImageField(upload_to='immagini_articoli/'),
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prodotti.categoria'),
        ),
    ]
