# Generated by Django 5.2.6 on 2026-09-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prodotti', '0054_alter_immaginiarticolo_articolo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immaginiarticolo',
            name='immagine',
            field=models.ImageField(default='/media/default_immagine_articolo/saniscope_logo 2.png', upload_to='immagini_articoli/'),
        ),
    ]
