# Generated by Django 5.2.6 on 2026-09-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prodotti', '0055_alter_immaginiarticolo_immagine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['pk'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorie'},
        ),
        migrations.AlterField(
            model_name='categoria',
            name='immagine_categoria',
            field=models.ImageField(default='/media/default_immagine_articolo/saniscope_logo 2.png', upload_to='immagini_categoria/'),
        ),
    ]
