# Generated by Django 5.2.6 on 2026-09-13 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prodotti', '0056_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedetecniche',
            name='articolo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scheda_rel', to='Prodotti.prodotto'),
        ),
    ]
