# Generated by Django 5.2.6 on 2026-09-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prodotti', '0057_alter_schedetecniche_articolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedetecniche',
            name='scheda',
            field=models.FileField(upload_to='schede_tecniche/'),
        ),
    ]
