# Generated by Django 5.2.6 on 2026-09-13 19:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prodotti', '0058_alter_schedetecniche_scheda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedetecniche',
            name='data_inizio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
