# Generated by Django 5.2.6 on 2026-09-13 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prodotti', '0059_alter_schedetecniche_data_inizio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='immagine_categoria',
            field=models.ImageField(default='default_immagine_articolo/saniscope_logo 2.png', upload_to='immagini_categoria/'),
        ),
    ]
