# Generated by Django 5.2.6 on 2026-09-13 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prodotti', '0060_alter_categoria_immagine_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immaginiarticolo',
            name='immagine',
            field=models.ImageField(default='default_immagine_articolo/saniscope_logo 2.png', upload_to='immagini_articoli/'),
        ),
    ]
