# Generated by Django 5.2.6 on 2026-09-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prodotti', '0063_categorie_senza_immagine_tornano_al_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='immagine_categoria',
            field=models.ImageField(default='default_immagine_articolo/saniscope_logo.png', upload_to='immagini_categoria/'),
        ),
        migrations.AlterField(
            model_name='immaginiarticolo',
            name='immagine',
            field=models.ImageField(default='default_immagine_articolo/saniscope_logo.png', upload_to='immagini_articoli/'),
        ),
    ]
