# Generated by Django 5.2.6 on 2026-07-27 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Carrello', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrello',
            options={'ordering': ['id'], 'verbose_name': 'Carrello', 'verbose_name_plural': 'Carrelli'},
        ),
    ]
