# Generated by Django 5.2.6 on 2026-09-12 19:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carrello', '0003_alter_carrello_options'),
        ('Prodotti', '0037_alter_prodotto_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='carrello',
            constraint=models.UniqueConstraint(fields=('cliente', 'prodotto'), name='vincolo_unico_cliente_prodotto'),
        ),
    ]
