# Generated by Django 5.2.6 on 2026-09-12 22:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carrello', '0004_carrello_vincolo_unico_cliente_prodotto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrello',
            name='quantita',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
