# Generated by Django 5.2.6 on 2026-09-12 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carrello', '0005_alter_carrello_quantita'),
        ('Prodotti', '0037_alter_prodotto_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrello',
            name='prodotto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementi_carrello', to='Prodotti.prodotto'),
        ),
    ]
